### ISSUE TITLE
Class scrreprt Error: undefined old font command `\bf'

### ISSUE THREAD

**Issue by 0xErnie** [MarkusAmshove/LaTeX-Vorlage-Berichtsheft#1]
Ich habe die aktuelle Version von LaTeX unter Archlinux installiert.

Wenn ich die Vorlage generieren möchte, bekomme ich folgenden Fehler:

> ! Class scrreprt Error: undefined old font command `\bf'.
> 
> See the scrreprt class documentation for explanation.

Einen Behelf fand ich hier:
http://tex.stackexchange.com/questions/67018/problem-with-moderncv-and-bf-inside-bibliography

Ich habe nicht gefunden wo \bf genutzt wird, mein LaTeX ist aber auch ein bisschen eingerostet.

**Comment by simon-mueller** [comment]
Es empfiehlt sich statt `\bf` einfach `\textbf` zu verwenden.
